require("core.plugin_config.auto-save")
require("core.plugin_config.guard")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.onedark")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
